version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smatrx-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: smatrx
      POSTGRES_PASSWORD: smatrx_dev_2024
      POSTGRES_DB: smatrx_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
